# Auto-generated from /home/asa/Desktop/t_go_test/t_GO_publication.py THEMES.
# Regenerate: python3 backend/scripts/regenerate_publication_themes.py [path/to/t_GO_publication.py]
from __future__ import annotations
from typing import Dict, FrozenSet, List

PUBLICATION_THEME_KEYWORDS: Dict[str, List[str]] = {
    'Stress & cytokine response': [
        'stress',
        'interferon',
        'cytokine',
        'inflammatory',
        'defense',
    ],
    'Inflammation & immune signaling': [
        'inflammation',
        'inflammatory',
        'tnf',
        'il-1',
        'il-6',
        'nf-kb',
        'toll-like',
        'interleukin',
        'chemokine',
        'ccl',
        'cxcl',
        'immune response',
        'inflammasome',
        'pattern recognition',
        'pathogen response',
    ],
    'Oxidative stress & redox regulation': [
        'oxidative',
        'redox',
        'reactive oxygen',
        'ros',
        'nitrosative',
        'nrf2',
        'antioxidant',
        'glutathione',
        'superoxide',
        'peroxidase',
        'peroxiredoxin',
        'sod',
        'catalase',
        'thioredoxin',
        'oxidoreductase',
        'hydrogen peroxide',
        'peroxide',
        'nitric oxide',
        'peroxynitrite',
        'nadph oxidase',
        'mitochondrial ros',
        'electron transport chain',
        'mitochondrial dysfunction',
        'oxidative damage',
        'protein oxidation',
        'lipid peroxidation',
        'dna oxidation',
        'redox imbalance',
    ],
    'Extracellular matrix & adhesion': [
        'extracellular',
        'matrix',
        'adhesion',
        'integrin',
        'collagen',
        'remodeling',
        'fibronectin',
        'laminin',
        'basement membrane',
        'mmp',
        'matrix metalloproteinase',
        'tenascin',
        'focal adhesion',
        'ecm',
        'tissue remodeling',
        'stromal',
        'scaffold',
        'matrisome',
        'cell junction',
        'cell adhesion',
        'cell-matrix',
        'desmosome',
    ],
    'Metabolic re-wiring': [
        'metabolic',
        'oxidoreductase',
        'catabolic',
        'fatty',
        'one-carbon',
        'biosynthetic',
    ],
    'Hematopoietic & immune commitment': [
        'hematopoiet',
        'myeloid',
        'lymphoid',
        'leukocyte',
        'granulocyte',
        'erythro',
        'megakary',
        'erythropoiet',
        'myelopoiet',
        'thrombopoiet',
        'lymphocyte',
        'monocyte',
        'neutrophil',
        'eosinophil',
        'basophil',
        'platelet',
        'erythrocyte',
        'anemia',
        'cytopenia',
        'pancytopenia',
        'thrombocytopenia',
        'leukopenia',
        'neutropenia',
        'immune cell',
        'blood cell',
        'hematologic',
        'hematopoiesis',
        'stem cell',
        'hsc',
    ],
    'Cell-cycle & Apoptosis': [
        'cell cycle',
        'mitotic',
        'chromosome',
        'checkpoint',
        'dna replication',
        'nuclear division',
        'apoptosis',
        'programmed cell death',
        'caspase',
    ],
    'Neuronal Excitability & Synapse': [
        'axon',
        'dendrite',
        'synapse',
        'neurotransmitter',
        'vesicle',
        'action potential',
        'ion channel',
        'potassium',
        'sodium',
        'calcium',
        'glutamate',
        'gaba',
        'synaptic',
        'neurogenesis',
        'axonogenesis',
    ],
    'Neurotrophic Signaling & Growth Factors': [
        'neurotrophin',
        'ngf',
        'bdnf',
        'ntf',
        'trk',
        'trka',
        'trkb',
        'gdnf',
        'growth factor',
        'igf',
        'egf',
        'fgf',
        'receptor tyrosine kinase',
    ],
    'Immune-Neuronal Crosstalk': [
        'microglia',
        'macrophage',
        'satellite glia',
        'neuroimmune',
        'neuroinflammation',
        'cd11b',
        'cd68',
        'csf1',
        'tslp',
        'complement',
        'ccr',
        'cxcr',
    ],
    'Pain & Nociception': [
        'pain',
        'nociception',
        'nociceptor',
        'hyperalgesia',
        'allodynia',
        'trpv1',
        'trpa1',
        'scn9a',
        'piezo',
        'itch',
        'sensory perception',
        'neuropeptide',
    ],
    'Oxidative Phosphorylation & Mitochondria': [
        'mitochondrial',
        'oxidative phosphorylation',
        'electron transport chain',
        'atp synthase',
        'complex i',
        'respiratory chain',
        'mitophagy',
    ],
    'Autophagy & Proteostasis': [
        'autophagy',
        'lysosome',
        'proteasome',
        'ubiquitin',
        'protein folding',
        'chaperone',
    ],
    'Myelination & Schwann Cell Biology': [
        'myelin',
        'schwann cell',
        'mbp',
        'mpz',
        'prx',
        'pmp22',
        'node of ranvier',
        'myelination',
        'myelin sheath',
        'axon ensheathment',
        'remyelination',
        'demyelination',
        'schwann cell differentiation',
        'schwann cell proliferation',
        'schwann cell migration',
        'axon guidance',
        'nerve regeneration',
    ],
    'Fibrosis': [
        'fibrosis',
        'fibrotic',
        'extracellular matrix',
        'matrix organization',
        'matrix remodeling',
        'collagen',
        'fibronectin',
        'laminin',
        'myofibroblast',
        'tissue remodeling',
        'tgf beta',
        'smad signaling',
        'emt',
        'endmt',
    ],
    'Adipose Tissue Development': [
        'adipose tissue',
        'adipogenesis',
        'adipocyte',
        'lipid storage',
        'lipogenesis',
        'ppar gamma',
        'c/ebp',
        'thermogenesis',
    ],
    'Allergy': [
        'allergy',
        'allergic',
        'hypersensitivity',
        'ige',
        'mast cell',
        'histamine',
        'th2',
        'il-4',
        'il-5',
        'il-13',
    ],
    'Bone remodeling & osteogenesis': [
        'osteogenesis',
        'bone formation',
        'bone development',
        'skeletal development',
        'ossification',
        'mineralization',
        'bone mineralization',
        'osteoblast',
        'osteoblast differentiation',
        'osteoblast proliferation',
        'osteoid',
        'bone matrix formation',
        'alkaline phosphatase',
        'runx2',
        'osterix',
        'sp7',
        'collagen type i',
        'osteoclast',
        'osteoclast differentiation',
        'osteoclastogenesis',
        'bone resorption',
        'tartrate-resistant acid phosphatase',
        'trap',
        'cathepsin k',
        'bone remodeling',
        'bone turnover',
        'skeletal homeostasis',
        'rank',
        'rankl',
        'opg',
        'wnt signaling',
        'beta-catenin',
        'bmp',
        'tgf beta',
        'smad signaling',
        'endosteal niche',
        'bone marrow niche',
        'osteolineage cell',
        'hematopoietic niche',
        'mesenchymal stem cell',
        'stromal cell',
        'bone matrix',
        'hydroxyapatite',
        'osteocalcin',
        'osteopontin',
        'sclerostin',
        'osteoporosis',
        'osteopenia',
        'bone loss',
    ],
    'Cardiac & Muscle Function': [
        'heart',
        'cardiac',
        'cardiomyocyte',
        'contraction',
        'sarcomere',
        'troponin',
        'myosin',
        'arrhythmia',
        'heart failure',
        'cardiomyopathy',
    ],
}

# Mirrors THEMES[...]["enabled"] is True in source file
PUBLICATION_DEFAULT_ENABLED_THEME_NAMES: FrozenSet[str] = frozenset(
    {
        'Stress & cytokine response',
        'Inflammation & immune signaling',
        'Oxidative stress & redox regulation',
        'Extracellular matrix & adhesion',
        'Metabolic re-wiring',
        'Hematopoietic & immune commitment',
        'Cell-cycle & Apoptosis',
        'Neurotrophic Signaling & Growth Factors',
        'Immune-Neuronal Crosstalk',
        'Pain & Nociception',
        'Oxidative Phosphorylation & Mitochondria',
        'Autophagy & Proteostasis',
    }
)

# Extra themes for Customize Theme UI only (not in t_GO_publication THEMES).
UI_ONTOLOGY_THEME_KEYWORDS: Dict[str, List[str]] = {
    'Membrane & Cell Surface': [
        'membrane',
        'plasma membrane',
        'cell surface',
        'membrane protein',
        'transmembrane',
        'integral membrane',
        'membrane transport',
        'ion channel',
    ],
    'Nucleus & Nuclear Processes': [
        'nucleus',
        'nuclear',
        'chromatin',
        'dna',
        'rna',
        'transcription',
        'nucleolus',
        'nuclear envelope',
        'nuclear pore',
        'chromosome',
    ],
    'Cytoplasm & Cytoskeleton': [
        'cytoplasm',
        'cytoskeleton',
        'microtubule',
        'actin',
        'intermediate filament',
        'microfilament',
        'centrosome',
        'centriole',
        'cilium',
        'flagellum',
    ],
    'Mitochondria & Energy': [
        'mitochondria',
        'mitochondrial',
        'atp',
        'energy',
        'respiration',
        'electron transport',
        'oxidative phosphorylation',
        'krebs cycle',
    ],
    'Endoplasmic Reticulum & Golgi': [
        'endoplasmic reticulum',
        'er',
        'golgi',
        'golgi apparatus',
        'vesicle',
        'secretory',
        'protein folding',
        'glycosylation',
        'trafficking',
    ],
}
